// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 KeyValueStore.com
//
// Writes kubernetes.js, the field names the Revision Viewer needs to show
// Kubernetes objects, from what "k8scodec schema" prints:
//
//   k8scodec schema > schema.json
//   node revisions/test/generate/make-schema.js schema.json 1.37.1
//
// Types that come out the same are kept once, so the file stays small.

'use strict';
// node --test runs every .js file under a test folder; this one only runs by hand.
if (process.env.NODE_TEST_CONTEXT) return;
const fs = require('fs');
const path = require('path');

const [file, version] = process.argv.slice(2);
if (!file || !version) { console.error('usage: node make-schema.js schema.json VERSION'); process.exit(2); }
const schema = JSON.parse(fs.readFileSync(file, 'utf8'));

const SPECIAL = { Time: 'T', MicroTime: 'M', Duration: 'D', FieldsV1: 'F', Quantity: 'Q', IntOrString: 'I', RawExtension: 'R', RawJSON: 'J' };
const BASIC = { string: 's', int: 'i', uint: 'u', bool: 'b', bytes: 'y', float: 'f' };
const WRAPPERS = { OrArray: 'A', OrBool: 'B', OrStringArray: 'S' };

// A type expression from k8scodec, with struct names replaced by ref(name).
function code(t, ref) {
  if (t.startsWith('*')) return '*' + code(t.slice(1), ref);
  if (t.startsWith('[]')) return '[' + code(t.slice(2), ref);
  if (t.startsWith('map:')) return '{' + code(t.slice(4), ref);
  if (t.startsWith('wrap:')) return 'W' + code(t.slice(5), ref);
  const w = /^(OrArray|OrBool|OrStringArray):(.+)$/.exec(t);
  if (w) return WRAPPERS[w[1]] + ref(w[2]);
  if (SPECIAL[t]) return SPECIAL[t];
  if (BASIC[t]) return BASIC[t];
  if (!(t in schema.types)) throw new Error('unknown type ' + t);
  return ref(t);
}
function fieldText(f, ref) {
  for (const c of f.name) if (/[\s|,]/.test(c)) throw new Error('a field name this format cannot hold: ' + f.name);
  const flags = (f.omitempty ? 'e' : '') + (f.omitzero ? 'z' : '') + (f.inline ? 'n' : '');
  return f.num + ',' + f.name + ',' + code(f.type, ref) + (flags ? ',' + flags : '');
}

// Partition refinement: types start in one class per shape and split until
// every class holds types whose fields point at the same classes.
const names = Object.keys(schema.types).sort();
let cls = new Map(names.map((n) => [n, 0]));
for (;;) {
  const sig = new Map();
  const next = new Map();
  for (const n of names) {
    const s = (schema.types[n] || []).map((f) => fieldText(f, (t) => '#' + cls.get(t))).join('|');
    if (!sig.has(s)) sig.set(s, sig.size);
    next.set(n, sig.get(s));
  }
  const before = new Set(cls.values()).size, after = sig.size;
  cls = next;
  if (after === before) break;
}
// Number the classes in the order the kinds reach them, so related types sit together.
const order = new Map();
const types = [];
function visit(n) {
  const c = cls.get(n);
  if (order.has(c)) return order.get(c);
  const i = types.length;
  order.set(c, i);
  types.push(null);
  types[i] = (schema.types[n] || []).map((f) => fieldText(f, (t) => String(visit(t)))).join('|');
  return i;
}
const kinds = {};
for (const k of Object.keys(schema.kinds).sort()) kinds[k] = visit(schema.kinds[k]);

const lines = [];
lines.push('// SPDX-License-Identifier: Apache-2.0');
lines.push('// Copyright 2026 KeyValueStore.com');
lines.push('//');
lines.push('// The fields of every kind of object Kubernetes ' + version + ' keeps in etcd, so the');
lines.push('// Revision Viewer can show an object with its field names, as kubectl does.');
lines.push('// Generated by test/generate/make-schema.js from Kubernetes\' own Go types');
lines.push('// (k8s.io/api, k8s.io/apimachinery, k8s.io/apiextensions-apiserver and');
lines.push('// k8s.io/kube-aggregator, Apache License 2.0, The Kubernetes Authors).');
lines.push('//');
lines.push('// kinds: "apiVersion Kind" to a type. types: each type\'s fields, split by');
lines.push('// "|", each "protobuf number,JSON name,type[,flags]". A type is s (string),');
lines.push('// i (integer), u (unsigned), b (bool), y (bytes), f (float), the number of');
lines.push('// another type, or one of Kubernetes\' own: T Time, M MicroTime, D Duration,');
lines.push('// F FieldsV1, Q Quantity, I IntOrString, R RawExtension, J JSON. In front:');
lines.push('// * pointer, [ list, { map from strings, W a list sent as a message, and');
lines.push('// A, B, S a CustomResourceDefinition schema that can also be a list, a bool or');
lines.push('// a list of strings. Flags: e omitempty, z omitzero, n inline.');
lines.push('(function (root, factory) {');
lines.push('  \'use strict\';');
lines.push('  const data = factory();');
lines.push('  if (typeof module === \'object\' && module.exports) module.exports = data;');
lines.push('  else root.KVKubernetes = data;');
lines.push('})(typeof globalThis !== \'undefined\' ? globalThis : this, function () {');
lines.push('  \'use strict\';');
lines.push('  return {');
lines.push('    version: ' + JSON.stringify(version) + ',');
lines.push('    kinds: {');
const kk = Object.keys(kinds);
kk.forEach((k, i) => lines.push('      ' + JSON.stringify(k) + ': ' + kinds[k] + (i < kk.length - 1 ? ',' : '')));
lines.push('    },');
lines.push('    types: [');
types.forEach((t, i) => lines.push('      ' + JSON.stringify(t) + (i < types.length - 1 ? ',' : '')));
lines.push('    ]');
lines.push('  };');
lines.push('});');
const out = path.join(__dirname, '..', '..', 'kubernetes.js');
fs.writeFileSync(out, lines.join('\n') + '\n');
console.log(out, fs.statSync(out).size, 'bytes,', Object.keys(kinds).length, 'kinds,', types.length, 'types (from ' + names.length + ')');
